title: Young Pirates of Europe
email: office@young-pirates.eu
description: >-
   Young Pirates of Europe is an association that brings together political youth organisations and other youth organisations in Europe that focus on pirate topics, such as topics surrounding usage and regulation of digital technologies, transparency in governance, fight against corruption in governance, topics surrounding drug substance usage and their regulation, engagement in democratic processes, and the protection of liberal democracies and the rule of law. We aim to provide an alternative to traditional European progressive parties and promote ideas that we believe are lacking in the political discourse. 

markdown: kramdown
theme: minima
